apiVersion: v1
kind: Pod
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  containers:
    - name: ollama-container
      image: ollama/ollama
      ports:
        - containerPort: 11434
      volumeMounts:
        - mountPath: /root/.ollama
          name: ollama-volume
  volumes:
    - name: ollama-volume
      hostPath:
        path: [path_to_volume] 
        type: Directory
